# -*- coding: utf-8 -*-
"""UPI.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19Qo7Dr2E9c8rgTfFYIWEM-rrwD7yOxaZ
"""

import numpy as np
import pandas as pd
# import os
from plotly.offline import init_notebook_mode, iplot, plot
import plotly as py
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.graph_objs as go

"""## **Data Analysis**"""

df_upi = pd.read_csv("/content/UPI apps transaction data in 2021.csv")
df_upi.head()

df_upi.info()

df_upi["UPI Banks"].unique()

"""### **Data visualisation**"""

trace1 = go.Scatter(
                    x = df_upi["Month"],
                    y = df_upi["Volume (Mn)"],
                    mode = "lines+markers",
                    name = "Volume (Mn)",
                    text= df_upi["UPI Banks"])
trace2 = go.Scatter(
                    x = df_upi["Month"],
                    y = df_upi["Value (Cr)"],
                    mode = "lines+markers",
                    name = "Value (Cr)",
                    text= df_upi["UPI Banks"])
trace3 = go.Scatter(
                    x = df_upi["Month"],
                    y = df_upi["Volume (Mn) By Costumers"],
                    mode = "lines+markers",
                    name = "Volume (Mn) By Costumers",
                    text= df_upi["UPI Banks"])
trace4 = go.Scatter(
                    x = df_upi["Month"],
                    y = df_upi["Value (Cr) by Costumers"],
                    mode = "lines+markers",
                    name = "Value (Cr) by Costumers",
                    text= df_upi["UPI Banks"])
data = [trace1, trace2, trace3, trace4 ]
layout = dict(title = 'Monthly Data of UPI Banks',
              xaxis= dict(title= 'UPI',ticklen= 5,zeroline= False)
             )
fig = dict(data = data, layout = layout)
iplot(fig)

"""** bold textBubble chart - Value of each bank based on month by month sales
**
"""

df_upi_b = df_upi.groupby(['UPI Banks', 'Month'], as_index=False)['Volume (Mn) By Costumers', 'Value (Cr) by Costumers', 'Value (Cr)', 'Volume (Mn)'].agg('sum')
df_bubble = df_upi_b.sort_values(by=['Value (Cr)'], ascending=False)

data = [
    {
        'y': df_bubble['Value (Cr)'],
        'x': df_bubble['Month'],
        'mode': 'markers',
        'marker': {
            'color': df_bubble['Month'],
            'showscale': False
        },
        "text" :  df_bubble['UPI Banks']
    }
]
iplot(data)

trace1 = go.Histogram(
    x = df_bubble['UPI Banks'],
    opacity=0.75,
    name = "UPI Banks")

data = [trace1]
layout = go.Layout(barmode='overlay',
                   title='Banks Active in Months',
                   xaxis=dict(title='UPI Banks Montly Activeness'),
                   yaxis=dict( title='Month'),
)
fig = go.Figure(data=data, layout=layout)
iplot(fig)

df_upi_dp = df_upi.drop(columns=["Month", "Year"])
df_upi_yearly = df_upi_dp.groupby(['UPI Banks'], as_index=False)['Volume (Mn) By Costumers', 'Value (Cr) by Costumers', 'Value (Cr)', 'Volume (Mn)'].agg('sum')
df_upi_yearly.head()

import plotly.graph_objs as go
# print(df_upi_yearly.columns)
sorted_df_value = df_upi_yearly.sort_values(by=['Value (Cr)'], ascending=False)[:5]
# print(sorted_df_value.columns)
# x = sorted_df_value['UPI Banks']

trace1 = {
  'x': sorted_df_value['UPI Banks'],
  'y': sorted_df_value['Value (Cr)'],
  'name': 'Value (Cr)',
  'type': 'bar'
};
trace2 = {
  'x': sorted_df_value['UPI Banks'],
  'y': sorted_df_value['Volume (Mn) By Costumers'],
  'name': 'Volume (Mn) By Costumers',
  'type': 'bar'
};
trace3 = {
  'x': sorted_df_value['UPI Banks'],
  'y': sorted_df_value['Value (Cr) by Costumers'],
  'name': 'Value (Cr) By Costumers',
   'type': 'bar'
};
trace4 = {
  'x': sorted_df_value['UPI Banks'],
  'y': sorted_df_value['Volume (Mn)'],
  'name': 'Volume (Mn)',
  'type': 'bar'
};
data = [trace1, trace2, trace3, trace4];
layout = {
  'xaxis': {'title': 'Top 5 Banks by Value in 2021'},
  'barmode': 'relative',
  'title': 'Value of top 5 Banks'
};
fig = go.Figure(data = data, layout = layout)
iplot(fig)

"""## **Top 5 banks**"""

sorted_df_value = df_upi_yearly.sort_values(by=['Value (Cr)'], ascending=False)[:5]
# pie1_list = [float(each.replace(',', '.')) for each in sorted_df_value['Value (Cr)']]
pie1_list = sorted_df_value['Value (Cr)']
labels = sorted_df_value['UPI Banks']
# figure
fig = {
  "data": [
    {
      "values": pie1_list,
      "labels": labels,
      "domain": {"x": [0, .5]},
      "name": "Value",
      "hoverinfo":"label+percent+name",
      "hole": .3,
      "type": "pie"
    },],
  "layout": {
        "title":"Value of top 5 UPI Banks",
        "annotations": [
            { "font": { "size": 20},
              "showarrow": False,
              "text": "",
                "x": 0.20,
                "y": 1
            },
        ]
    }
}
iplot(fig)